---
- hosts: localhost
  connection: local
  vars:
    user: write your username here
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: "webserver_{{ msrg }}"
      location: northeurope
      tags:
          solution: "webserver_{{ msrg }}"
          delete: ansibletraining
    register: rg
  - debug:
      var: rg
